basePath: /v1
definitions:
  main.LoginAccessPayload:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 100
        type: string
    required:
    - email
    - password
    type: object
  main.RegisterAccessPayload:
    properties:
      email:
        maxLength: 100
        type: string
      password:
        maxLength: 100
        minLength: 8
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - username
    type: object
  store.Account:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
paths:
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: feteches
      parameters:
      - description: Account Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/store.Account'
        "400":
          description: Bad Request
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApyKeyAuth: []
      tags:
      - Accounts
  /login:
    post:
      consumes:
      - application/json
      description: asx
      parameters:
      - description: Account Credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.LoginAccessPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Account Registered
          schema:
            $ref: '#/definitions/store.Account'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
  /register:
    post:
      consumes:
      - application/json
      description: asx
      parameters:
      - description: Account Credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.RegisterAccessPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Account Registered
          schema:
            $ref: '#/definitions/store.Account'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
securityDefinitions:
  ApikeyAuth:
    in: header
    name: Autorization
    type: apiKey
swagger: "2.0"
